name: tech-experience-society-certificate
services:
  app:
    image: archlinux:latest
    container_name: mydevcontainer
    working_dir: /app
    ports:
      - "8080:5173"
      - "8081:8081"
    volumes:
      - .:/app 
    command: sh -c "pacman -Syu --noconfirm && pacman -S --noconfirm nodejs npm && npm install --legacy-peer-deps && npm install -g orion && (orion &) && exec npm run dev"
        
